version = 0.1

[default.build.parameters]
# profile = "deepak_personal"

[default.deploy.parameters]
stack_name = "django-lambda-stack"
region = "us-east-1"
# profile = "deepak_personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# image_repository = "503561447119.dkr.ecr.us-east-1.amazonaws.com/django"
disable_rollback = false
